### ISSUE TITLE
有時候會抓到以前沒有的課號 KeyError 

### ISSUE THREAD

**Issue by jiazheng0609** [jiazheng0609/NCNU-course-alert#11]
```
取得所有課程資料： 20210913_141623
Traceback (most recent call last):
  File "fileDiff.py", line 118, in <module>
    if bot.prevAns[courseID]['chosen'] != curCourse['chosen']:
KeyError: '5100190'

```

**Comment by jiazheng0609** [comment]
其實在開始搶課前這 bug 就存在了，有一些課號會突然出現，只是我一直還沒修，都是手動重開XD

**Comment by snsd0805** [comment]
@jiazheng0609 Same
```
取得所有課程資料： 20210913_160527
Traceback (most recent call last):
  File "fileDiff.py", line 118, in <module>
    if bot.prevAns[courseID]['chosen'] != curCourse['chosen']:
KeyError: '2290210'
```
應該加個 Exception handling 忽略就好了

**Comment by jiazheng0609** [comment]
想看這有沒有奏效，還要看機會 @@

**Comment by jiazheng0609** [comment]
而且第一階段網路選課已經截止啦，我們 9/23 再會～

**Comment by jiazheng0609** [comment]
ㄟㄟ怎麼自動 close 了XDD

**Comment by jiazheng0609** [comment]
應該沒問題啦
