### ISSUE TITLE
Incompatible with >=20.0 version of python-telegram-bot

### ISSUE THREAD

**Issue by jiazheng0609** [jiazheng0609/NCNU-course-alert#14]
When running using Python 3.8 and latest version of python-telegram-bot, I get:
```
Traceback (most recent call last):
  File "fileDiff.py", line 9, in <module>
    from bot import CourseAlertBot
  File "/home/pi/NCNU-course-alert/bot.py", line 7, in <module>
    updater = Updater(token=config['TG_BOT']['TOKEN'], use_context=True)
TypeError: __init__() got an unexpected keyword argument 'token'
```

A quick search of error message I found this similar issue:
https://github.com/python-telegram-bot/python-telegram-bot/issues/3504
Suggesting that we should follow this guide to upgrade our code, to be compatible with v20 python-telegram-bot:
https://github.com/python-telegram-bot/python-telegram-bot/wiki/Transition-guide-to-Version-20.0
## Operating System
Raspbian GNU/Linux 10 (buster)

## Version of Python, python-telegram-bot & dependencies
```
$ python -m telegram
python-telegram-bot 20.5
Bot API 6.8
Python 3.8.18 (default, Sep  5 2023, 02:17:07)  [GCC 8.3.0]
```

**Comment by jiazheng0609** [comment]
I think we can freeze the python-telegram-bot version in Pipfile first, before someone done the upgrade in our main code.
